sudo: false

env:
  - DB=postgres://localhost/igihe2

language: node_js

node_js:
  - 'stable'

notifications:
  email: false

cache:
  npm: false

services:
  - postgresql

script:
  - npm test

after_success:
  - npm run coveralls
